## 1.Giống và khác

In [4]:
x = 1
x = 'Python'
print(x)

Python


In [5]:
print(3**4)

81


In [7]:
print("python")

python


## 2.Kiểu dữ liệu

In [8]:
#Tự động chuyển đổi kiểu
a = 1
b = 2.0
c = a + b
print(c)

3.0


In [9]:
#Ép kiểu
#string -> number
float_number = float('2021')
int_number = int('2021')
print(float_number, int_number)

2021.0 2021


In [10]:
#number->string
year = str(2021)

In [15]:
#Thao tác với string
name = 'Summer ' + str(2021)
print(name)
name = '*' * 5
print(name)
name = 'Data {} {}'.format('Science', 2021);
print(name)

Summer 2021
*****
Data Science 2021


In [2]:
#Split
list_1 = 'Data Science 2021'.split()
list_2 = 'Data--Science--2021'.split('--')
print(list_1)
print(list_2)

['Data', 'Science', '2021']
['Data', 'Science', '2021']


In [3]:
#Join
list_1 = ['Data', 'Science', '2021']
name = '--'.join(list_1)
print(name)

Data--Science--2021


In [4]:
#Replace 
'Data Science'.replace('e', '-')

'Data Sci-nc-'

In [9]:
#Isspace
a = ' '.isspace()
b = '/t/t'.isspace()
c = '-'.isspace()
print("a: {}, b: {}, c: {}".format(a, b, c))

a: True, b: False, c: False


In [10]:
#Isalpha
a = 'abcde'.isalpha()
b = 'abcd123'.isalpha()
print("a: {}, b: {}".format(a, b))

a: True, b: False


In [11]:
#Isdigit
a = '123'.isdigit()
b = 'abcd123'.isdigit()
print("a: {}, b: {}".format(a, b))

a: True, b: False


In [17]:
#Kiểu list
#Initialization
list_a = [1,2,3,4,5]
list_b = range(5) #[0,1,2,3,4]
list_c = range(1,10,2) #[1,3,5,7,9]
list_d = range(5,1,-1) #[5,4,3,2]
list_e = [x for x in range(10) if x % 2 == 0]
list_e

[0, 2, 4, 6, 8]

In [19]:
list_f = []
list_f.append('Data')
list_f.append('Science')
list_f.append(2021)
list_f

['Data', 'Science', 2021]

In [31]:
#Retrieve elements from list
src = range(10)
a = src[:7]
b = src[3:]
c = src[3:7]
d = src[:-1]
e = src[:-2]

In [23]:
#Get number of elements
length = len(src)

In [24]:
src = ['Data', 'Science', 2021]
for index, element in enumerate(src):
    print(index, element)

0 Data
1 Science
2 2021


In [25]:
#Check existence
exp_1 = 'Data' in src
exp_2 = 2021 not in src
print('exp_1: {}, exp_2: {}'.format(exp_1,exp_2))

exp_1: True, exp_2: False


In [1]:
#Sort a list
src = [(3, 'A'), (2, 'C'), (1, 'D'), (4, 'B')]
src.sort()
print(src)

[(1, 'D'), (2, 'C'), (3, 'A'), (4, 'B')]


In [6]:
src.sort(key=lambda tuple: -tuple[0])
src

[(4, 'B'), (3, 'A'), (2, 'C'), (1, 'D')]

In [42]:
#Delete an element
src = [1,2,3,4,5]
del src[3]
src

[1, 2, 3, 5]

In [47]:
#Merge lists
a = [1,2,3,4,5]
b = ['A','B','C','D']
c = ['x','y','z']
d = zip(a,b,c)
for e in d:
    print(e)

(1, 'A', 'x')
(2, 'B', 'y')
(3, 'C', 'z')


In [48]:
#Kiểu tuple
src = (1,2,3)
src[2] = 5 #immutable object

TypeError: 'tuple' object does not support item assignment

In [49]:
src = [(20, 7, 'Session 1'), (21, 7, 'Session 2')]

In [51]:
#Kiểu set
src = [1,1,1,1,1,2,2,2,2,3,3,3,3,3]
reduced_list = list(set(src))
reduced_list

[1, 2, 3]

In [52]:
#Kiểu dictionary
#Initialize
dict = {}
dict['A'] = 1
dict['B'] = 2
dict

{'A': 1, 'B': 2}

In [53]:
'A' in dict

True

In [54]:
'C' in dict

False

In [55]:
dict.keys()

dict_keys(['A', 'B'])

In [56]:
dict.values()

dict_values([1, 2])

## 3.If statement

In [57]:
a = False
b = 1
if a and b != 1:
    print('One')
elif b == 1:
    print('Two')
else:
    print('Three')

Two


## 4. Loop

In [58]:
src = range(10)
for i in src:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [60]:
i = 0
while i < len(src):
    print(src[i])
    i += 1

0
1
2
3
4
5
6
7
8
9


## 5. File manipulation

In [63]:
#Read file
with open('file.txt') as f:
    content = f.read()
print(content)

Hello world from a file


In [64]:
#Write to a file
with open('file.txt', 'w') as f:
    content = f.write('Data Science Lab')

## 6. Exception Handler

In [65]:
try:
    division = 10/0
except ZeroDivisionError:
    print("Division by zero occurs")

Division by zero occurs


## 7. Assert

In [68]:
a = 5
b = 0
assert b != 0 , "Division by zero"
c = a / b

AssertionError: Division by zero

## 8. Function

In [69]:
#Define a function
def do_sum(a, b):
    return a + b
print(do_sum(3, 5))

8


In [70]:
#Parameters with default value
def do_sum(a, b = 5):
    return a + b
print(do_sum(3))

8


In [72]:
#Nested function
def do_sum(a, b):
    def decrease(value):
        return value - 1
    return decrease(a + b)
do_sum(3, 5)

7

## 9. OOP

In [74]:
class Person:
    def __init__(self, name, age, phone):
        self._name = name
        self._age = age
        self._phone = phone
        self._selected_items = []
    
    def select(self, item):
        self._selected_items.append(item)
    
    def get_info(self):
        return 'Name: {}\nAge: {}\nPhone number: {}\n'.format(self._name, self._age, self._phone)

In [75]:
nam = Person('Nam', 18, 123456)
nam.select('Book')
nam.select('Pen')
print(nam._selected_items)
print(nam.get_info())

['Book', 'Pen']
Name: Nam
Age: 18
Phone number: 123456



## 10. Numpy

In [77]:
import numpy as np

In [89]:
np_array_1 = np.array([1,2,3])
np_array_1

array([1, 2, 3])

In [87]:
np_array_2 = np.array(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [88]:
np_array_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
#Add
np_array_1 + np_array_2

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [91]:
#Subtract
np_array_1 - np_array_2

array([[ 0,  0,  0],
       [-3, -3, -3],
       [-6, -6, -6]])

In [92]:
np_array_1.dot(np_array_2)

array([30, 36, 42])

In [93]:
np_array_1 / np_array_2

array([[1.        , 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ],
       [0.14285714, 0.25      , 0.33333333]])

In [95]:
np_array_2.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [97]:
np_array = np.array([
    [1, 5],
    [2, 6]
])

In [98]:
np.linalg.inv(np_array)

array([[-1.5 ,  1.25],
       [ 0.5 , -0.25]])